version: '3.9'
services:
  youtuber:
    build:
      context: ./
      dockerfile: ./src/youtuber/Dockerfile
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    networks:
      - youtuber
  db:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - youtuber
    volumes:
      - /data/super-potato/db:/data/db
  fronter-server:
    build:
      context: ./
      dockerfile: ./src/fronter/server/Dockerfile
    environment:
      - SESSION_HOST=session
    env_file:
      - ./src/fronter/server/.env
    ports:
      - '3001:3001'
    networks:
      - session
  session:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - session

networks:
  youtuber:
    driver: bridge
  session:
    driver: bridge
