version: '3.9'
services:
  youtuber:
    build:
      context: ./
      dockerfile: ./src/youtuber/Dockerfile
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    networks:
      - main
  db:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - main
    volumes:
      - /data/super-potato/db:/data/db
  fronter-server:
    build:
      context: ./
      dockerfile: ./src/fronter/server/Dockerfile
      args:
        GITHUB_PACKAGE_TOKEN: ${SUPER_POTATO_PACKAGE_TOKEN}
    environment:
      - SESSION_HOST=session
      - DB_HOST=db
    env_file:
      - ./src/fronter/server/.env
    ports:
      - '3001:3001'
    networks:
      - main
    depends_on:
      - session
      - db
  session:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - main

networks:
  main:
    driver: bridge
