FROM node:latest

LABEL maintainer="Linus Ljung <linus.ljung@outlook.com>"

ENV PROJECT_DIR=/var/www
ENV PORT=<%= port %>

EXPOSE ${PORT}

COPY ./tsconfig.json ${PROJECT_DIR}/tsconfig.json
COPY ./src/<%= name %> ${PROJECT_DIR}/src/<%= name %>

WORKDIR ${PROJECT_DIR}/src/<%= name %>

RUN npm install
RUN npm run build

ENTRYPOINT [ "npm", "start" ]
